import Head from "next/head";
import Sidebar from "../components/Sidebar";
import styled from "styled-components";

export default function Home() {
  return (
    <MainContainer>
      <Head>
        <title>What's App 2.0</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Sidebar />
    </MainContainer>
  );
}

const MainContainer = styled.div`
  width: 100%;
  display: flex;
`;
